### ISSUE TITLE
Bump to TeXLive 2019

### ISSUE THREAD

**Issue by m-kuhn** [urdh/texlive-blob#1]
Would be nice to get an update for this year.

PS: Thanks a lot for this repository, it's really handy :+1:

**Comment by m-kuhn** [comment]
I have created a forked repo to get it running for now. https://github.com/opengisch/texlive-blob/releases/tag/20190724

This is just meant as a temporary solution, I do not have any plans to duplicate maintenance effort. But if you need help, let me know so we can discuss the possibilities.

**Comment by urdh** [comment]
Done! Sorry for the delay, it's been a while since I've had time to fiddle with my TeX projects.

**Comment by m-kuhn** [comment]
Thanks a lot :+1:
